Repository nextcloud/appstore, pull requests merged in 2020-04, with the labels that each got.

#687 Change sorting description
  nextcloudappstore/core/templates/app/list.html
Labels: design

#688 Changing descriptions in "Search"
  nextcloudappstore/core/templates/nav.html
Labels: design

#690 Adding question mark
  nextcloudappstore/core/templates/account/login.html
Labels: design

#680 Update CRL due to revoked spgverein.crt
  nextcloudappstore/certificate/nextcloud.crl
Labels: security

#692 Update CRL due to certificate overlap
  nextcloudappstore/certificate/nextcloud.crl
Labels: hardening
