Repository nextcloud/appstore, pull requests merged in 2023-12, with the labels that each got.

#1233 fix: use correct name for .php-cs-fixer.dist.php
  .gitignore
  nextcloudappstore/scaffolding/app-templates/24/app/.gitignore
  nextcloudappstore/scaffolding/app-templates/24/app/.php-cs-fixer.dist.php
  nextcloudappstore/scaffolding/app-templates/25/app/.gitignore
  nextcloudappstore/scaffolding/app-templates/25/app/.php-cs-fixer.dist.php
Labels: bug, 3. to review

#1259 chore: update workflows from templates
  .github/workflows/pr-feedback.yml
Labels: dependencies, automated, 3. to review

#1256 Comments: Report / Flag Review Spam
  CHANGELOG.md
  nextcloudappstore/core/caching.py
  nextcloudappstore/core/fixtures/licenses.json
  nextcloudappstore/core/migrations/0027_apprating_appeal.py
  nextcloudappstore/core/models.py
  nextcloudappstore/core/serializers.py
  nextcloudappstore/core/static/assets/app/api/Ratings.ts
  nextcloudappstore/core/static/assets/app/api/RatingsSpec.ts
  nextcloudappstore/core/static/assets/app/app/dom/Ratings.ts
  nextcloudappstore/core/static/assets/app/app/templates/Ratings.ts
  nextcloudappstore/core/static/assets/app/app/views/Detail.ts
  nextcloudappstore/core/static/assets/css/style.css
  nextcloudappstore/core/static/assets/css/theme.css
  nextcloudappstore/core/templates/app/detail.html
  nextcloudappstore/core/tests/test_rating_deletion_log.py
  nextcloudappstore/core/views.py
  nextcloudappstore/user/templates/user/appeal-comments.html
  nextcloudappstore/user/templates/user/base.html
  nextcloudappstore/user/urls.py
  nextcloudappstore/user/views.py
Labels: enhancement
