Repository nextcloud/appstore, pull requests merged in 2023-05, with the labels that each got.

#852 Make changelog parser with v prefix
  nextcloudappstore/api/v1/release/parser.py
  nextcloudappstore/api/v1/tests/data/changelogs/CHANGELOG_v.md
  nextcloudappstore/api/v1/tests/test_parser.py
Labels: enhancement

#1026 updated prod install guide
  docs/prodinstall.rst
  scripts/maintenance/update.sh
Labels: docs

#1050 chore: update workflows from templates
  .github/workflows/command-rebase.yml
  .github/workflows/fixup.yml
Labels: dependencies, automated, 3. to review

#1052 bring info.xsd up-to-date with the one in server
  nextcloudappstore/api/v1/release/info.xsd
Labels: dependencies
