Repository nextcloud/appstore, pull requests merged in 2024-04, with the labels that each got.

#1354 fix(docs): Adjust contributing guidelines link
  README.md
Labels: bug, 3. to review

#1356 fix(docs): Replace IRC with Talk room
  .github/CONTRIBUTING.md
Labels: 3. to review

#1360 Updating pr-feedback.yml workflow from template
  .github/workflows/pr-feedback.yml
Labels: dependencies
