Repository nextcloud/appstore, pull requests merged in 2024-09, with the labels that each got.

#1461 fix: Align dashboard icon with Nextcloud 30 design
  nextcloudappstore/core/static/assets/img/icons/categories/view-dashboard-white.svg
  nextcloudappstore/core/static/assets/img/icons/categories/view-dashboard.svg
Labels: bug, design, 3. to review

#1457 Update developer.rst
  docs/developer.rst
Labels: bug, docs, 3. to review, feedback-requested

#1458 chore: update workflows from templates
  .github/workflows/pr-feedback.yml
Labels: dependencies, automated, 3. to review
