Repository nextcloud/appstore, pull requests merged in 2024-12, with the labels that each got.

#1515 fix(version): Fix unstable version handling
  nextcloudappstore/core/models.py
Labels: bug

#1518 implemented Odoo integration(newsletter mail list)
  nextcloudappstore/settings/base.py
  nextcloudappstore/user/forms.py
  nextcloudappstore/user/management/commands/create_missing_profiles.py
  nextcloudappstore/user/migrations/0001_initial.py
  nextcloudappstore/user/models.py
  nextcloudappstore/user/odoo.py
  nextcloudappstore/user/views.py
  poetry.lock
  pyproject.toml
Labels: python

#1517 fix: Typo in app name hint - it is PascalCase not camelCase
  nextcloudappstore/scaffolding/forms.py
Labels: bug, low priority, python, 3. to review
